name: notes
description: Simple note taking app

publish_to: 'none' 

version: 1.1.0+12

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  fluent_ui: ^3.9.0
  get: ^4.6.1
  container_tab_indicator: ^0.3.0
  flutter_staggered_grid_view: ^0.6.1
  path_provider: ^2.0.9
  path: ^1.8.0
  intl: ^0.17.0
  scientisst_db: ^0.1.2
  focused_menu: ^1.0.5
  filesize: ^2.0.1
  flutter_switch: ^0.3.2
  share_plus: ^3.1.0
  flutter_signin_button: ^2.0.0
  dynamic_themes: ^1.1.0
  shared_preferences: ^2.0.13
  package_info_plus: ^1.4.0
  package_info_plus_web: ^1.0.4
  package_info_plus_windows: ^1.0.4
  google_sign_in: ^5.2.4
  google_sign_in_web: ^0.10.0+5
  firebase_auth: ^3.3.9
  firebase_auth_web: ^3.3.9
  firebase_core: ^1.13.1
  firebase_core_web: ^1.6.1
  cloud_firestore: ^3.1.10
  cloud_firestore_web: ^2.6.10
  clipboard: ^0.1.3
  detectable_text_field: ^2.0.3
  flutter_link_previewer: ^2.6.3
  flutter_chat_types: ^3.3.1
  linkify: ^4.1.0
  html: ^0.15.0
  http: ^0.13.4
  meta: ^1.7.0
  url_launcher: ^6.0.20
  provider: ^6.0.2
  dynamic_color: ^0.1.0
  dynamic_colorscheme: ^1.0.0
  material_color_utilities: ^0.1.3
  reorderables: ^0.4.3
  excel: ^2.0.0-null-safety-3
  permission_handler: ^9.2.0
  permission_handler_windows: ^0.1.0
  flutter_widget_from_html: ^0.8.5
  flutter_widget_from_html_core: ^0.8.5+1
  flutter_screenutil: ^5.4.0
  open_document: ^1.0.4
  google_fonts: ^2.3.1
  emojis: ^0.9.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  rename: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/