name: notes
description: Simple note taking app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <=3.3.1"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  fluent_ui: ^3.9.0
  get: ^4.6.1
  container_tab_indicator: ^0.3.0
  flutter_staggered_grid_view: ^0.6.1
  path_provider: ^2.0.9
  path: ^1.8.0
  intl: ^0.17.0
  scientisst_db: ^0.1.2
  focused_menu: ^1.0.5
  filesize: ^2.0.1
  flutter_switch: ^0.3.2
  share_plus: ^4.0.4
  flutter_signin_button: ^2.0.0
  # dynamic_themes: ^1.1.0
  shared_preferences: ^2.0.13
  package_info_plus: ^1.4.0
  package_info_plus_web: ^1.0.4
  package_info_plus_windows: ^1.0.4
  google_sign_in: ^5.4.1
  firebase_auth: ^3.9.0
  firebase_auth_web: ^4.4.1
  firebase_core: ^1.22.0
  firebase_core_web: ^1.6.1
  cloud_firestore: ^3.1.10
  cloud_firestore_web: ^2.6.10
  clipboard: ^0.1.3
  detectable_text_field: ^2.0.3
  flutter_link_previewer: ^2.6.3
  flutter_chat_types: ^3.3.1
  linkify: ^4.1.0
  html: ^0.15.0
  http: ^0.13.4
  meta: ^1.7.0
  url_launcher: ^6.0.20
  provider: ^6.0.2
  dynamic_color: ^1.5.4
  material_color_utilities: ^0.1.4
  reorderables: ^0.5.0
  excel: ^2.0.0-null-safety-3
  permission_handler: ^10.0.0
  permission_handler_windows: ^0.1.0
  flutter_html: ^2.2.1
  flutter_screenutil: ^5.4.0
  # open_document: ^1.0.4
  google_fonts: ^3.0.1
  emojis: ^0.9.9
  currency_picker: ^2.0.9
  firebase_messaging: ^11.4.0
  flutter_local_notifications: ^9.4.1
  timezone: ^0.8.0
  flutter_native_timezone: ^2.0.0
  flutter_expandable_fab: ^1.5.1
  about: ^2.1.1
  in_app_update: ^3.0.0
  in_app_review: ^2.0.4
  peekanapp: ^0.0.1
  flutter_shortcuts: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  rename: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - CHANGELOG.md
    - README.md
    - CONTRIBUTING.md
    - assets/images/
    - assets/lottie/