// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtJnXpPFqVNo6MoUqm2bWG6ju5zOYPdg4',
    appId: '1:93929877833:web:19b842c09190ba77432a98',
    messagingSenderId: '93929877833',
    projectId: 'notes-dd515',
    authDomain: 'notes-dd515.firebaseapp.com',
    storageBucket: 'notes-dd515.appspot.com',
    measurementId: 'G-YNGX3D1Z86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo8G7b3GTJlfsVaUlOdUkyX2kqkh-gNak',
    appId: '1:93929877833:android:eb9b2f01e444638c432a98',
    messagingSenderId: '93929877833',
    projectId: 'notes-dd515',
    storageBucket: 'notes-dd515.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUowJh8dEOqGP_Equi5sLW5R8hi8W29Ls',
    appId: '1:93929877833:ios:63b70058ba3753a6432a98',
    messagingSenderId: '93929877833',
    projectId: 'notes-dd515',
    storageBucket: 'notes-dd515.appspot.com',
    androidClientId: '93929877833-hf68n8clihn9fmfp1fb05dk2qe9679td.apps.googleusercontent.com',
    iosClientId: '93929877833-k47275p26qdhtocoidmqe10k0dpsmr9h.apps.googleusercontent.com',
    iosBundleId: 'com.example.notes',
  );
}
