/// Flutter icons NotesIcon
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NotesIcon
///      fonts:
///       - asset: fonts/NotesIcon.ttf
///
///
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
///
import 'package:flutter/widgets.dart';

class NotesIcon {
  NotesIcon._();

  static const _kFontFam = 'NotesIcon';
  static const String? _kFontPkg = null;

  static const IconData payments =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cog =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reminders =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData routine =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // ignore: constant_identifier_names
  static const IconData ruppe_notes =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData schedule =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData school =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // ignore: constant_identifier_names
  static const IconData send_message =
      IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings =
      IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // ignore: constant_identifier_names
  static const IconData small_arrow_left =
      IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // ignore: constant_identifier_names
  static const IconData small_arrow_right =
      IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // ignore: constant_identifier_names
  static const IconData sound_settings =
      IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData subscriptions =
      IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // ignore: constant_identifier_names
  static const IconData system_error =
      IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData template =
      IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // ignore: constant_identifier_names
  static const IconData traction_history =
      IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // ignore: constant_identifier_names
  static const IconData up_arrow =
      IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_1 =
      IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData voice =
      IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallpaper =
      IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // ignore: constant_identifier_names
  static const IconData wi_fi =
      IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // ignore: constant_identifier_names
  static const IconData alarm =
      IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData budget =
      IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // ignore: constant_identifier_names
  static const IconData button_arrow_left =
      IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // ignore: constant_identifier_names
  static const IconData button_arrow_right =
      IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar =
      IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // ignore: constant_identifier_names
  static const IconData coin_gift_box =
      IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // ignore: constant_identifier_names
  static const IconData cred_protect =
      IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // ignore: constant_identifier_names
  static const IconData credit_card =
      IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // ignore: constant_identifier_names
  static const IconData display_settings =
      IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // ignore: constant_identifier_names
  static const IconData down_arrow =
      IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData error =
      IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info =
      IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lists =
      IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logo =
      IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // ignore: constant_identifier_names
  static const IconData nav_arrow_left =
      IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // ignore: constant_identifier_names
  static const IconData nav_arrow_right =
      IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // ignore: constant_identifier_names
  static const IconData near_me =
      IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData network =
      IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // ignore: constant_identifier_names
  static const IconData no_vouchers =
      IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData note =
      IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // ignore: constant_identifier_names
  static const IconData map_marker =
      IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData magnifier =
      IconData(0xe86f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
